<?php

use App\Http\Controllers\ApiController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EscortController;
use App\Http\Controllers\MpesaController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Public Routes
|--------------------------------------------------------------------------
| Routes that can be accessed without authentication.
| Example: Home page, public escorts listing, etc.
*/

Route::get('/', function () {
    return Inertia::render('Frontend/Home');
});

// Public resource routes (accessible without auth)
Route::resources([
    'escort' => EscortController::class,
]);

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
| Routes that require authentication and email verification.
| Example: Dashboard, conversations, messages, API actions.
*/

Route::middleware(['auth', 'verified'])->group(function () {

    /*
    |--------------------------------------------------------------------------
    | Dashboard Route
    |--------------------------------------------------------------------------
    */
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    /*
    |--------------------------------------------------------------------------
    | Chat Route
    |--------------------------------------------------------------------------
    */
    Route::get('/chat', [ChatController::class, 'index'])->name('chat.index');
    Route::get('/chat/users', [ChatController::class, 'getUsers'])->name('chat.users');
    Route::get('/chat/{conversation}', [ChatController::class, 'show'])->name('chat.show');

    Route::post('/chat/start', [ChatController::class, 'startConversation'])->name('chat.start');
    Route::post('/chat/send', [ChatController::class, 'sendMessage'])->name('chat.send');
    Route::post('/chat/{conversation}/read', [ChatController::class, 'markAsRead'])->name('chat.read');
    Route::post('/chat/{conversation}/typing', [ChatController::class, 'typing'])->name('chat.typing');
    Route::post('/chat/{conversation}/archive', [ChatController::class, 'toggleArchive'])->name('chat.archive');
    Route::post('/chat/{conversation}/mute', [ChatController::class, 'toggleMute'])->name('chat.mute');
    Route::post('/chat/{conversation}/block', [ChatController::class, 'toggleBlock'])->name('chat.block');

    Route::delete('/chat/{conversation}', [ChatController::class, 'destroy'])->name('chat.destroy');

    /*
    |--------------------------------------------------------------------------
    | User Management
    |--------------------------------------------------------------------------
    */
    Route::prefix('user-management')->group(function () {
        Route::post('/unlock-phone', [ApiController::class, 'unlockPhone'])->name('phone.unlock');
        Route::post('/mpesa/stk-push', [MpesaController::class, 'stkPush'])->name('mpesa.stk-push');
    });

    /*
    |--------------------------------------------------------------------------
    | Favorites
    |--------------------------------------------------------------------------
    */
    Route::post('/favorites/toggle', [ApiController::class, 'toggleFavorite'])->name('favorites.toggle');

    /*
    |--------------------------------------------------------------------------
    | Heartbeat Route
    |--------------------------------------------------------------------------
    */
    Route::get('/heartbeat', function () {
        return response()->json(['status' => 'ok']);
    })->middleware(['throttle:10,1'])->name('heartbeat');
});

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
| Routes generated by Laravel Breeze / Jetstream / custom auth system.
*/
require __DIR__ . '/auth.php';
