<?php

use App\Http\Controllers\ApiController;
use App\Http\Controllers\ConversationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EscortController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\MpesaController;
use Illuminate\Support\Facades\Broadcast;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Public Routes
|--------------------------------------------------------------------------
| Routes that can be accessed without authentication.
| Example: Home page, public escorts listing, etc.
*/

Route::get('/', function () {
    return Inertia::render('Frontend/Home');
});

// Public resource routes (accessible without auth)
Route::resources([
    'escort' => EscortController::class,
]);

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
| Routes that require authentication and email verification.
| Example: Dashboard, conversations, messages, API actions.
*/

Route::middleware(['auth', 'verified'])->group(function () {

    // Dashboard route
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Resource routes for conversations and messages
    Route::resources([
        'conversation' => ConversationController::class,
        // 'message' => MessageController::class,
    ]);

    Route::name('api.')->group(function () {
        Route::get('/conversations', [MessageController::class, 'conversations'])->name('conversations.index');
        Route::get('/conversations/{conversation}/messages', [MessageController::class, 'messages'])->name('conversations.messages');
        Route::post('/messages', [MessageController::class, 'store'])->name('messages.store');




        Route::post('/messages/typing', [MessageController::class, 'typing'])->name('messages.typing');
        Route::post('/messages/{message}/read', [MessageController::class, 'markAsRead']);
        Route::delete('/messages/{message}', [MessageController::class, 'destroy']);
    });

    // API routes for authenticated users
    Route::post('/unlock-phone', [ApiController::class, 'unlockPhone'])->name('phone.unlock');
    Route::post('/mpesa/stk-push', [MpesaController::class, 'stkPush'])->name('mpesa.stk-push');

    /*
    |--------------------------------------------------------------------------
    | Heartbeat Route
    |--------------------------------------------------------------------------
    */
    Route::get('/heartbeat', function () {
        return response()->json(['status' => 'ok']);
    })->middleware(['throttle:10,1'])->name('heartbeat');
});

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
| Routes generated by Laravel Breeze / Jetstream / custom auth system.
*/
require __DIR__ . '/auth.php';
